serviceMaps:
  serviceName: request-service
  mappings:
    - version: 1.0
      description: Persists water tanker application detail
      fromTopic: create-water-tanker-booking
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_tanker_booking_details(booking_id, booking_no, tenant_id, address_detail_id, mobile_number, tanker_type, water_type, tanker_quantity, water_quantity, description, applicant_uuid, delivery_date, delivery_time, extra_charge, vendor_id, vehicle_id, driver_id, vehicle_type, vehicle_capacity, booking_createdby, booking_status, locality_code, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::DATE, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.bookingNo
            - jsonPath: $.waterTankerBookingDetail.tenantId
            - jsonPath: $.waterTankerBookingDetail.addressDetailId
            - jsonPath: $.waterTankerBookingDetail.mobileNumber
            - jsonPath: $.waterTankerBookingDetail.tankerType
            - jsonPath: $.waterTankerBookingDetail.waterType
            - jsonPath: $.waterTankerBookingDetail.tankerQuantity
            - jsonPath: $.waterTankerBookingDetail.waterQuantity
            - jsonPath: $.waterTankerBookingDetail.description
            - jsonPath: $.waterTankerBookingDetail.applicantUuid
            - jsonPath: $.waterTankerBookingDetail.deliveryDate
            - jsonPath: $.waterTankerBookingDetail.deliveryTime
            - jsonPath: $.waterTankerBookingDetail.extraCharge
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.vehicleType
            - jsonPath: $.waterTankerBookingDetail.vehicleCapacity
            - jsonPath: $.waterTankerBookingDetail.bookingCreatedBy
            - jsonPath: $.waterTankerBookingDetail.bookingStatus
            - jsonPath: $.waterTankerBookingDetail.localityCode
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_tanker_booking_details_auditdetails SELECT * FROM public.upyog_rs_tanker_booking_details WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId

    - version: 1.0
      description: Persists water tanker application detail
      fromTopic: create-water-tanker-booking-isprofiledisabled
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_tanker_booking_details(booking_id, booking_no, tenant_id, address_detail_id, mobile_number, tanker_type, water_type, tanker_quantity, water_quantity, description, applicant_uuid, delivery_date, delivery_time, extra_charge, vendor_id, vehicle_id, driver_id, vehicle_type, vehicle_capacity, booking_createdby, booking_status, locality_code, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::DATE, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.bookingNo
            - jsonPath: $.waterTankerBookingDetail.tenantId
            - jsonPath: $.waterTankerBookingDetail.addressDetailId
            - jsonPath: $.waterTankerBookingDetail.mobileNumber
            - jsonPath: $.waterTankerBookingDetail.tankerType
            - jsonPath: $.waterTankerBookingDetail.waterType
            - jsonPath: $.waterTankerBookingDetail.tankerQuantity
            - jsonPath: $.waterTankerBookingDetail.waterQuantity
            - jsonPath: $.waterTankerBookingDetail.description
            - jsonPath: $.waterTankerBookingDetail.applicantUuid
            - jsonPath: $.waterTankerBookingDetail.deliveryDate
            - jsonPath: $.waterTankerBookingDetail.deliveryTime
            - jsonPath: $.waterTankerBookingDetail.extraCharge
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.vehicleType
            - jsonPath: $.waterTankerBookingDetail.vehicleCapacity
            - jsonPath: $.waterTankerBookingDetail.bookingCreatedBy
            - jsonPath: $.waterTankerBookingDetail.bookingStatus
            - jsonPath: $.waterTankerBookingDetail.localityCode
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_tanker_applicant_details(applicant_id, booking_id, name, mobile_number, email_id, alternate_number, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail.applicantDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.applicantId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.name
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.mobileNumber
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.emailId
            - jsonPath: $.waterTankerBookingDetail.applicantDetail.alternateNumber
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_tanker_address_details(address_id, applicant_id, house_no, address_line_1, address_line_2, street_name, landmark, city, city_code, locality, locality_code, pincode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail.address
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.address.addressId
            - jsonPath: $.waterTankerBookingDetail.address.applicantId
            - jsonPath: $.waterTankerBookingDetail.address.houseNo
            - jsonPath: $.waterTankerBookingDetail.address.addressLine1
            - jsonPath: $.waterTankerBookingDetail.address.addressLine2
            - jsonPath: $.waterTankerBookingDetail.address.streetName
            - jsonPath: $.waterTankerBookingDetail.address.landmark
            - jsonPath: $.waterTankerBookingDetail.address.city
            - jsonPath: $.waterTankerBookingDetail.address.cityCode
            - jsonPath: $.waterTankerBookingDetail.address.locality
            - jsonPath: $.waterTankerBookingDetail.address.localityCode
            - jsonPath: $.waterTankerBookingDetail.address.pincode

        - query: INSERT INTO public.upyog_rs_tanker_booking_details_auditdetails SELECT * FROM public.upyog_rs_tanker_booking_details WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId

    - version: 1.0
      description: Update water tanker application detail
      fromTopic: update-water-tanker-booking
      isTransaction: true
      queryMaps:
        - query: UPDATE public.upyog_rs_tanker_booking_details SET booking_status = ?, vendor_id = ?, vehicle_id = ?, driver_id = ?, payment_receipt_filestore_id = ?, createdby = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingStatus
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.paymentReceiptFilestoreId
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime
            - jsonPath: $.waterTankerBookingDetail.bookingId

        - query: INSERT INTO public.upyog_rs_tanker_booking_details_auditdetails SELECT * FROM public.upyog_rs_tanker_booking_details WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId

    
    - version: 1.0
      description: Persists mobile toilet booking detail
      fromTopic: create-mobile-toilet-booking
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details(booking_id, booking_no, tenant_id, address_detail_id, mobile_number, no_of_mobile_toilet, delivery_from_date, delivery_to_date, delivery_from_time, delivery_to_time, description, applicant_uuid, vendor_id, vehicle_id, driver_id, booking_createdby, booking_status, locality_code, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?::DATE, ?::DATE, ?::TIME, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId
            - jsonPath: $.mobileToiletBookingDetail.bookingNo
            - jsonPath: $.mobileToiletBookingDetail.tenantId
            - jsonPath: $.mobileToiletBookingDetail.addressDetailId
            - jsonPath: $.mobileToiletBookingDetail.mobileNumber
            - jsonPath: $.mobileToiletBookingDetail.noOfMobileToilet
            - jsonPath: $.mobileToiletBookingDetail.deliveryFromDate
            - jsonPath: $.mobileToiletBookingDetail.deliveryToDate
            - jsonPath: $.mobileToiletBookingDetail.deliveryFromTime
            - jsonPath: $.mobileToiletBookingDetail.deliveryToTime
            - jsonPath: $.mobileToiletBookingDetail.description
            - jsonPath: $.mobileToiletBookingDetail.applicantUuid
            - jsonPath: $.mobileToiletBookingDetail.vendorId
            - jsonPath: $.mobileToiletBookingDetail.vehicleId
            - jsonPath: $.mobileToiletBookingDetail.driverId
            - jsonPath: $.mobileToiletBookingDetail.bookingCreatedBy
            - jsonPath: $.mobileToiletBookingDetail.bookingStatus
            - jsonPath: $.mobileToiletBookingDetail.localityCode
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdTime
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedTime
        
        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details_auditdetails SELECT * FROM public.upyog_rs_mobile_toilet_booking_details WHERE booking_id = ?;
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId

    - version: 1.0
      description: Persists mobile toilet booking detail
      fromTopic: create-mobile-toilet-booking-isprofiledisabled
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details(booking_id, booking_no, tenant_id, address_detail_id, mobile_number, no_of_mobile_toilet, delivery_from_date, delivery_to_date, delivery_from_time, delivery_to_time, description, applicant_uuid, vendor_id, vehicle_id, driver_id, booking_createdby, booking_status, locality_code, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?::DATE, ?::DATE, ?::TIME, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId
            - jsonPath: $.mobileToiletBookingDetail.bookingNo
            - jsonPath: $.mobileToiletBookingDetail.tenantId
            - jsonPath: $.mobileToiletBookingDetail.addressDetailId
            - jsonPath: $.mobileToiletBookingDetail.mobileNumber
            - jsonPath: $.mobileToiletBookingDetail.noOfMobileToilet
            - jsonPath: $.mobileToiletBookingDetail.deliveryFromDate
            - jsonPath: $.mobileToiletBookingDetail.deliveryToDate
            - jsonPath: $.mobileToiletBookingDetail.deliveryFromTime
            - jsonPath: $.mobileToiletBookingDetail.deliveryToTime
            - jsonPath: $.mobileToiletBookingDetail.description
            - jsonPath: $.mobileToiletBookingDetail.applicantUuid
            - jsonPath: $.mobileToiletBookingDetail.vendorId
            - jsonPath: $.mobileToiletBookingDetail.vehicleId
            - jsonPath: $.mobileToiletBookingDetail.driverId
            - jsonPath: $.mobileToiletBookingDetail.bookingCreatedBy
            - jsonPath: $.mobileToiletBookingDetail.bookingStatus
            - jsonPath: $.mobileToiletBookingDetail.localityCode
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdTime
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_mobile_toilet_applicant_details(applicant_id, booking_id, name, mobile_number, email_id, alternate_number, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: mobileToiletBookingDetail.applicantDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.applicantDetail.applicantId
            - jsonPath: $.mobileToiletBookingDetail.applicantDetail.bookingId
            - jsonPath: $.mobileToiletBookingDetail.applicantDetail.name
            - jsonPath: $.mobileToiletBookingDetail.applicantDetail.mobileNumber
            - jsonPath: $.mobileToiletBookingDetail.applicantDetail.emailId
            - jsonPath: $.mobileToiletBookingDetail.applicantDetail.alternateNumber
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdTime
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_mobile_toilet_address_details(address_id, applicant_id, house_no, address_line_1, address_line_2, street_name, landmark, city, city_code, locality, locality_code, pincode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: mobileToiletBookingDetail.address
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.address.addressId
            - jsonPath: $.mobileToiletBookingDetail.address.applicantId
            - jsonPath: $.mobileToiletBookingDetail.address.houseNo
            - jsonPath: $.mobileToiletBookingDetail.address.addressLine1
            - jsonPath: $.mobileToiletBookingDetail.address.addressLine2
            - jsonPath: $.mobileToiletBookingDetail.address.streetName
            - jsonPath: $.mobileToiletBookingDetail.address.landmark
            - jsonPath: $.mobileToiletBookingDetail.address.city
            - jsonPath: $.mobileToiletBookingDetail.address.cityCode
            - jsonPath: $.mobileToiletBookingDetail.address.locality
            - jsonPath: $.mobileToiletBookingDetail.address.localityCode
            - jsonPath: $.mobileToiletBookingDetail.address.pincode
        
        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details_auditdetails SELECT * FROM public.upyog_rs_mobile_toilet_booking_details WHERE booking_id = ?;
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId


    - version: 1.0
      description: Update mobile Toilet booking detail
      fromTopic: update-mobile-toilet-booking
      isTransaction: true
      queryMaps:
        - query: UPDATE public.upyog_rs_mobile_toilet_booking_details SET booking_status = ?, vendor_id = ?, vehicle_id = ?, driver_id = ?, payment_receipt_filestore_id = ?, createdby = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE booking_id = ?;
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingStatus
            - jsonPath: $.mobileToiletBookingDetail.vendorId
            - jsonPath: $.mobileToiletBookingDetail.vehicleId
            - jsonPath: $.mobileToiletBookingDetail.driverId
            - jsonPath: $.mobileToiletBookingDetail.paymentReceiptFilestoreId
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedTime
            - jsonPath: $.mobileToiletBookingDetail.bookingId

        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details_auditdetails SELECT * FROM public.upyog_rs_mobile_toilet_booking_details WHERE booking_id = ?;
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId
